# GL NAV DOMESTIC INTERCONNECTIVITY MAPS
# FAST FACTS AND TALKING POINTS
# Last Updated: MARCH 12, 2024

# INPUT FILES NEEDED ####

# IN SOURCE FILE LOCATION/ FOLDER
# ... GL Talking Points template spreadsheet
# ... national rankings spreadsheet from WCSC: save as WCSC_tonnagebystate_CY##.xlsx
# ... national cargo and trips spreadsheet (All Regions) from IWR/WCSC: save as Cargo_20##-20## All Regions 10yrs.xlsx

# IMPORTANT: you must save these files using very specific file names, to feed them through this R code

# WHERE TO GET NATIONAL RANKINGS
#  The national rankings spreadsheet is generated by WCSC every year, and is accessible through:
# ... WCSC Website > Commerce Data > Ports and States Data (Available in Excel format here) > 
# ... select relevant calendar year
# ... Object title: Waterborne Commerce Statistics Center: CY 20## waterborne tonnage by state
# ... Download xlsx file, SAVE WITH THIS NAMING CONVENTION -- WCSC_tonnagebystate_CY##.xlsx
# ... Several tabs, e.g., Port_by_Tons
# ... Columns: RANK, PORT_NAME

# WHERE TO GET CARGO AND TRIPS DATA
#  This is a very large file with several 100,000s of rows of data.
# ... WCSC Website > Commerce Data > Waterborne Cargo and Trips Data Files > 
# ... Select link with naming convention: Cargo_20##-20## All Regions 10yrs
# ... download xlsx file and use same naming convention
# ... Columns: Waterway, WaterwayName, TrafficCode, TrafficName, Commodity, etc.

# ---

# RECENT UPDATES TO CODE ####

# FY23
# ... FY22 talking points and fast facts highlighted shipment/receipt/thru/intraport data for ONE CY YEAR ONLY.
# ... FY23 talking points and fast facts highlight shipment/receipt/thru/intraport data for 5 YEAR AVERAGE.
# ... minor changes: FY23 file naming convention and set working directory

# FY24
# ... FY24  a looooooot of stuff

# ---

# UPDATE MANUALLY ####

# Set the project directory. Note: Inputs folder contains all raw data needed to run this code "Inputs/..."
setwd("C:/Users/h5pmldfb/OneDrive - US Army Corps of Engineers/PAO Project")

# Manually update FY every year
FY <- 2023

# Manually exclude ports for later calculate_ranking Function (Filter by )
Excluded_ports <- c(3001, 3101, 3191, 3201, 3230, 3301, 3401, 3501, 3601, 3701, 3802, 3810, 3811, 3850, 3901, 3999)

# SEARCH FOR "UPDATE IN FY2024"

# ---

# MAIN BODY OF CODE ####
# Calculate calendar year based on fiscal year
calendar_year <- FY - 2

# Calculate short version of fiscal year (e.g., FY23)
FY_short <- FY - 2000

# Calculate short version of calendar year (e.g., 23)
calendar_short <- calendar_year - 2000

# Load necessary libraries. Install packages if not done yet 'install.packages("my_package")'
library(readxl)
library(openxlsx)
library(tidyr)
library(dplyr)
library(stringr)
library(writexl)
library(purrr)

# Function to read tonnage and direction data for all ports nationally. File "Cargo2012-2021 All Regions"
read_tonnage_data <- function(calendar_year) {
  # Construct the file path based on the calendar year
  file_path <- paste0("Inputs/Cargo", calendar_year - 9, "-", calendar_year, " All Regions.xlsx")
  # Check if the file exists
  if (file.exists(file_path)) {
    # Read the Excel file
    data <- read_xlsx(file_path)
    return(data)  # Return the data frame
  } else {
    stop("File not found:", file_path)  # Throw an error if the file is not found
  }
}
#Store the result in the 'data' dataset/frame by calling the above function.
data <- read_tonnage_data(calendar_year)

# Run this lines to View the excluded ports 
View_Excluded_ports <- data %>%
    dplyr::filter(WaterwayCode %in% Excluded_ports) %>%
    select(WaterwayCode, WaterwayName)%>%
    distinct(WaterwayCode, .keep_all = TRUE)
  View(View_Excluded_ports)

# Function to read harbor data and filter out specific harbors . File "Cargo2012-2021 All Regions"
read_harbor_data <- function() {
  file_path <- "Inputs/GL_Talking_Points_CY21.xlsx"
  if (file.exists(file_path)) {
    # Read the Excel file and filter specific harbors
    harbors <- read_xlsx(file_path, sheet = "Harbors") %>%
      dplyr::filter(Harbor != "Indiana (Northern District), IN" & Harbor != "Buffington, IN")
    # Correct spelling mistake in harbor name
    harbors$Harbor[harbors$Harbor == "Detour, MI"] <- "DeTour, MI"
    return(harbors)  # Return the filtered harbor data
  } else {
    stop("File not found:", file_path)  # Throw an error if the file is not found
  }
}
#Store the result in the 'harbors' dataset/frame by calling the above function.
harbors <- read_harbor_data()

# Function to read national rankings for top 150 ports. File "WCSC_tonnagebystate_CY21"   
read_national_rankings <- function(filename, sheet_name) {
  tryCatch({
    # Read file
    national_rankings <- read_xlsx(filename, sheet = sheet_name)
    
    # Remove empty rows and set correct column names
    national_rankings <- national_rankings %>% slice(4:n())
    colnames(national_rankings) <- national_rankings[1,]
    national_rankings <- national_rankings[-1,]
    
    return(national_rankings)
  }, error = function(e) {
    print(paste("Error reading file:", e$message))
    # Return NULL or an empty data frame to indicate failure
    return(NULL)
  })
}
#Store the result in the 'national_rankings' dataset/frame by calling the above function.
national_rankings <- read_national_rankings("Inputs/WCSC_tonnagebystate_CY21.xlsx", "Port_by_Name")

# Function to create the rankings and add to carry on data
calculate_ranking <-function(data, year, exclude_codes) {
  # Filter tonnage and direction data for GL data. Look only at most recent 5 years
  gl_data <- data %>%
    dplyr::filter((CompletedYear > year - 5 & CompletedYear <= year) & (WaterwayCode < 4000 & WaterwayCode > 3000))
  
  # Replace NA values in WaterwayName with empty strings
  gl_data$WaterwayName[is.na(gl_data$WaterwayName)] <- ""
  
  # Calculate ranking of WaterwayName based on total tons (tons), sharing the same rank for tied values
  gl_ranking <- gl_data %>%
    #Filter data based on conditions, excluding ports specified by their codes.
    filter(
      CompletedYear == year &
        !(WaterwayCode %in% exclude_codes)
    ) %>%
    # Group data by WaterwayName
    group_by(WaterwayName) %>%
    # Calculate total tons for each WaterwayName
    summarize(tons = sum(ShortTons)) %>%
    # Arrange data in descending order of total tons
    arrange(desc(tons)) %>%
    # Add a new column 'rank' with the rank of each WaterwayName based on total tons
    mutate(rank = dense_rank(desc(tons))) %>%
    rename(WaterwayName_Ranked = WaterwayName,
           tons_Ranked = tons,
           rank = rank)
  
  # Add NA values to gl_ranking to match the number of rows in gl_data while keeping the data manipulation within a single matrix.
  gl_ranking_full <- bind_rows(gl_ranking, data.frame(WaterwayName_Ranked = rep("", nrow(gl_data) - nrow(gl_ranking)),#rep("" creates empty instead of NA
                                                      tons_Ranked = rep(NA, nrow(gl_data) - nrow(gl_ranking)),
                                                      rank = rep(NA, nrow(gl_data) - nrow(gl_ranking))))
  
  # Add ranking information to gl_data as 3 new vectors
  gl_data <- cbind(gl_data, gl_ranking_full)
  
  return(gl_data)
}
#Store the result in the 'gl_data' dataset/frame by calling the above function.
gl_data <- calculate_ranking(data, calendar_year, Excluded_ports)

# Function to read ReconsRED data from an Excel file and manipulate it for fastfacts
read_ReconsRED <- function(filename, sheet_name) {
  tryCatch({
    # Read file
    ReconsRED <- read_xlsx(filename, sheet = sheet_name)
    
    # Rename columns
    colnames(ReconsRED) <- c("Port_Name", "Tonnage_CY2021", "Direct", "Indirect_Induced", "Business_Revenue", "Labor_Income")
    
    # Calculate total_jobs
    ReconsRED <- ReconsRED %>%
      mutate(total_jobs = Direct + Indirect_Induced)
    
    # Round up total_jobs
    ReconsRED$total_jobs <- ceiling(ReconsRED$total_jobs)
    
    # Function to convert to million format
    convert_to_million <- function(x) {
      # Check if x is numeric
      if (is.numeric(x)) {
        # Round to one decimal place
        x <- round(x, 1)
        # If x is greater than or equal to 1 million
        if (x >= 1e6) {
          # Convert to million format
          return(paste0(format(round(x / 1e6, 1), nsmall = 1)))
        } else {
          # Otherwise, return original value
          return(as.character(x))
        }
      } else {
        return(as.character(x))
      }
    }
    
    # Apply function to Labor_Income and Business_Revenue columns
    ReconsRED$Labor_Income <- sapply(ReconsRED$Labor_Income, convert_to_million)
    ReconsRED$Business_Revenue <- sapply(ReconsRED$Business_Revenue, convert_to_million)
    
    # Return manipulated dataset
    return(ReconsRED)
  }, error = function(e) {
    # Handle error
    print(paste("Error reading file:", e$message))
    # Return NULL or an empty data frame to indicate failure
    return(NULL)
  })
}
# Store the result in the 'ReconsRED' dataset/frame by calling the above function
ReconsRED <- read_ReconsRED("Inputs/RECONS_RED_Contribution_(FY24_CY2021).xlsx", "Sheet1RAW")


# Create table of fast facts for domestic interconnectivity maps
fast_facts <- function(harbor) {
  
  total_tons <- gl_data %>% dplyr::filter(WaterwayName == harbor) %>% group_by(CompletedYear) %>% summarize(tons = sum(ShortTons))
  
  # Recent tons = tons from target CY
  # Avg tonnage = 5-year average in all directions for harbor
  
  if (length(total_tons[[2]]) == 0) {
    avg_tonnage_5_yr <- data.frame(0)
    recent_tons <- data.frame(0,0)
  } else {
    avg_tonnage_5_yr <- total_tons %>% summarize(avg_tons = round(mean(tons),0))
    recent_tons <- total_tons %>% dplyr::filter(CompletedYear == calendar_year)
  }
  
  if (length(recent_tons[[2]]) == 0) {recent_tons <- data.frame(0,0)}
  
  # Shipping/ Receiving/ Thru/ Intraport = 5-year averages
      # Define a function to calculate the 5-year averages and handle cases where no data is found
      calculate_average <- function(data, harbor, category) {
        result <- data %>%
          dplyr::filter(WaterwayName == harbor & `In/Out/Thru` == category) %>%
          summarize(shipping_tons = sum(ShortTons) / 5)
        
        if (length(result[[1]]) == 0) {
          result <- data.frame(shipping_tons = 0)
        }
        
        return(result)
      }
      
      # Calculate the averages for each category
      shipping <- calculate_average(gl_data, harbor, "Outbound Shipping")
      receiving <- calculate_average(gl_data, harbor, "Inbound Receiving")
      thru <- calculate_average(gl_data, harbor, "Thru")
      intraport <- calculate_average(gl_data, harbor, "Local")
  
  # Commodities
  # POTENTIAL UPDATE: ADD IF STATEMENT FOR COMMODITIES WITH LESS THAN < 1% / >99% ####
      
      # Calculate total commodities
      total_commodities <- gl_data %>%
        dplyr::filter(WaterwayName == harbor) %>%
        group_by(CommodityName) %>%
        summarize(tons = sum(ShortTons) / 5) %>%
        mutate(percent = round((tons / avg_tonnage_5_yr[[1]] * 100), 0))
      
      top_3_commod <- top_n(total_commodities, 3, tons)# Get top 3 commodities
      
      # Format top commodities
      top_commods <- ifelse(nrow(top_3_commod) == 0,
                            data.frame(NA),
                            ifelse(nrow(top_3_commod) == 1,
                                   data.frame(paste0(top_3_commod[[1, 1]], " (", top_3_commod[[1, 3]], "%)")),
                                   ifelse(nrow(top_3_commod) == 2,
                                          data.frame(paste0(top_3_commod[[1, 1]], " (", top_3_commod[[1, 3]], "%), ", top_3_commod[[2, 1]], " (", top_3_commod[[2, 3]], "%)")),
                                          data.frame(paste0(top_3_commod[[1, 1]], " (", top_3_commod[[1, 3]], "%), ", top_3_commod[[2, 1]], " (", top_3_commod[[2, 3]], "%), ", top_3_commod[[3, 1]], " (", top_3_commod[[3, 3]], "%)"))
                                   ))
                            )
          # Calculate shipping commodities
          ship_comm <- gl_data %>%
            dplyr::filter(WaterwayName == harbor & `In/Out/Thru` == "Outbound Shipping") %>%
            group_by(CommodityName) %>%
            summarize(tons = sum(ShortTons) / 5) %>%
            mutate(percent = round((tons / shipping[[1]] * 100), 0))
          
          # Get top shipping commodities
          top_shipping <- ifelse(nrow(ship_comm) == 0,
                                 "NA",
                                 data.frame(paste0(top_n(ship_comm, 1)[[1, 1]], "(", top_n(ship_comm, 1)[[1, 3]], "%)"))
          )
          
          # Calculate receiving commodities
          recv_comm <- gl_data %>%
            dplyr::filter(WaterwayName == harbor & `In/Out/Thru` == "Inbound Receiving") %>%
            group_by(CommodityName) %>%
            summarize(tons = sum(ShortTons) / 5) %>%
            mutate(percent = round((tons / receiving[[1]] * 100), 0))
          
          # Get top receiving commodities
          top_recv <- ifelse(nrow(recv_comm) == 0,
                             "NA",
                             data.frame(paste0(top_n(recv_comm, 1)[[1, 1]], "(", top_n(recv_comm, 1)[[1, 3]], "%)"))
          )
                            
  # Formats rankings for fast facts table
  # Convert RANK column to integer
  national_rankings$RANK <- as.integer(national_rankings$RANK)
  
    # Check if there is a Great Lakes ranking for the specified harbor
    gl_rank <- gl_data$rank[gl_data$WaterwayName_Ranked == harbor]
    gl_rank <- ifelse(length(gl_rank) > 0, paste0("Great Lakes (", gl_rank, 
                                                  ifelse(gl_rank %% 10 == 1 & gl_rank != 11, "st)",
                                                         ifelse(gl_rank %% 10 == 2 & gl_rank != 12, "nd)", 
                                                                ifelse(gl_rank %% 10 == 3 & gl_rank != 13, "rd)", "th)")))),
                      "Great Lakes (NA)")
    
    # Check if there is a National ranking for the specified harbor
    national_rank <- national_rankings$RANK[national_rankings$PORT_NAME == harbor]
    national_rank <- ifelse(length(national_rank) > 0, paste0(" National (", national_rank,
                                                              ifelse(national_rank %% 10 == 1 & national_rank != 11, "st)",
                                                                     ifelse(national_rank %% 10 == 2 & national_rank != 12, "nd)",
                                                                            ifelse(national_rank %% 10 == 3 & national_rank != 13, "rd)", "th)")))),
                            " National (NA)")
    
    # Create dataframe variable for factssheet table
    # The table includes the rankings for the specified harbor in both Great Lakes and National contexts
    harbor_ranking <- paste0(gl_rank, ",", national_rank)
  
  #Ranks  Separated/alone  
    gl_rank_alone <- gl_data$rank[gl_data$WaterwayName_Ranked == harbor]
    gl_rank_alone <- ifelse(length(gl_rank_alone) > 0, paste0(gl_rank_alone, 
                                                        ifelse(gl_rank_alone %% 10 == 1 & gl_rank_alone != 11, "st",
                                                               ifelse(gl_rank_alone %% 10 == 2 & gl_rank_alone != 12, "nd", 
                                                                      ifelse(gl_rank_alone %% 10 == 3 & gl_rank_alone != 13, "rd", "th"))))
                            ,"")
                                                              
    national_rank_alone  <- national_rankings$RANK[national_rankings$PORT_NAME == harbor]
    national_rank_alone  <- ifelse(length(national_rank_alone) > 0, paste0(national_rank_alone,
                                                                                        ifelse(national_rank_alone %% 10 == 1 & national_rank_alone != 11, "st",
                                                                                               ifelse(national_rank_alone %% 10 == 2 & national_rank_alone != 12, "nd",
                                                                                                      ifelse(national_rank_alone %% 10 == 3 & national_rank_alone != 13, "rd", "th")))) 
                                   ,"")

  #More Facts
  Bussiness_Revenue <- "IDK How MUCh"
  Created_jobs <- "infinite -1 "
  LaboborInc_Trans<- "we do not want to wrok for real"
  # UPDATED IN JAN 2024: FOLLOW NEW SIG FIG AND ROUNDING CONVENTION 
  # All values in millions with 2 sig figs. Any values < 10,000 tons = "< 0.01 Million"
  
  if (avg_tonnage_5_yr[[1]] > 0) {
    if (avg_tonnage_5_yr[[1]]/10000 > 1) {
      avg_tonnage_5_yr[[1]] <- paste0(signif(avg_tonnage_5_yr[[1]]/1000000,2), " Million") 
    } else {
      avg_tonnage_5_yr[[1]] <- "<0.01 Million"
    }
  }
  if (recent_tons[[2]] > 0) {
    if (recent_tons[[2]]/10000 > 1) {
      recent_tons[[2]] <- paste0(signif(recent_tons[[2]]/1000000,2), " Million") 
    } else {
      recent_tons[[2]] <- "<0.01 Million"
    }
  }
  if (shipping[[1]] > 0) {
    if (shipping[[1]]/10000 > 1) {
      shipping[[1]] <- paste0(signif(shipping[[1]]/1000000,2), " Million") 
    } else {
      shipping[[1]] <- "<0.01 Million"
    }
  }
  if (receiving[[1]] > 0) {
    if (receiving[[1]]/10000 > 1) {
      receiving[[1]] <- paste0(signif(receiving[[1]]/1000000,2), " Million") 
    } else {
      receiving[[1]] <- "<0.01 Million"
    }
  }
  if (intraport[[1]] > 0) {
    if (intraport[[1]]/10000 > 1) {
      intraport[[1]] <- paste0(signif(intraport[[1]]/1000000,2), " Million") 
    } else {
      intraport[[1]] <- "<0.01 Million"
    }
  }
  if (thru[[1]] > 0) {
    if (thru[[1]]/10000 > 1) {
      thru[[1]] <- paste0(signif(thru[[1]]/1000000,2), " Million") 
    } else {
      thru[[1]] <- "<0.01 Million"
    }
  }
  
  # UPDATED IN JAN 2024: Order of tonnage table --> fast facts table
  # NOTE: do NOT change order of tonnage table if you can help it. You would also need to make tedious changes to talking points code.
  
  
  
  table <- data.frame(" ",
                      gl_rank_alone[[1]],
                      national_rank_alone[[1]],
                      harbor_ranking[[1]],
                      recent_tons[[2]], 
                      " ",
                      avg_tonnage_5_yr[[1]],
                      shipping[[1]], 
                      receiving[[1]], 
                      thru[[1]], 
                      intraport[[1]], 
                      top_commods[[1]],  
                      top_shipping[[1]], 
                      top_recv[[1]],
                      Bussiness_Revenue,## potencially new vars 
                      Created_jobs,
                      LaboborInc_Trans
  )
  
  colnames(table) <- c("2021 Highlights",
                       "Great Lakes Ranking",
                       "National Ranking",
                       "Harbor Ranking",
                       paste0(calendar_year, " Tonnage"),
                       "5-Year Averages",
                       paste0(calendar_year-4,"-",calendar_year," Average Tonnage"),
                       paste0(calendar_year-4, "-", calendar_year, " Avg. Shipments"), 
                       paste0(calendar_year-4, "-", calendar_year, " Avg. Receipts"), 
                       paste0(calendar_year-4, "-", calendar_year, " Avg. Thru"),
                       paste0(calendar_year-4, "-", calendar_year, " Avg. Intraport"), 
                       "Top Three Commodities Handled", 
                       "Primary Commodity Shipped", 
                       "Primary Commodity Received",
                       paste0(calendar_year-4,"-",calendar_year," Bussiness Revenue"),
                       " Created Jobs", 
                       " Labobor Income Trans"
  )
  
  table <- data.frame(t(table))
  colnames(table) <- c(paste0("Fast Facts - ", harbor))
  return(table)
  
}
# Load Fast Facts table into workbook / run fast facts function
wb <- loadWorkbook("Inputs/GL Talking Points Template.xlsx")

#Run one loop at the time and then run this last  2 lines of code:)

#Talking points Version 1 Loop (i.e. Monroe, MI had 2.2 Million tons move through the harbor in 2021, and averaged 1.7 Million tons over
#...the past 5 years from 2017-2021. Monroe is the 26th largest commercial harbor on the Great Lakes and the 116th largest harbor in the nation. 
#... On average, between 2017-2021, the harbor shipped 0.059 Million tons and received 1.6 Million tons annually. The top commodities handled at 
#... Monroe are Asphalt, Tar & Pitch (6%), Coal & Lignite (72%), Limestone (16%). The largest commodity shipped is Slag(49%) . 
#... The largest commodity received is Coal & Lignite(74%) .)
for (each in 1:length(harbors$Harbor)) {
  
  tonnage_table <- fast_facts(harbors$Harbor[each])
  
  if (each == 1) {
    writeData(wb, sheet = "Tonnage_Tables", tonnage_table, startCol = 1, startRow = 1, rowNames = TRUE)
  } else {
    writeData(wb, sheet = "Tonnage_Tables", tonnage_table, startCol = 1, startRow = ((each-1)*18)+1, rowNames = TRUE)
  }
  
  short_harbor <- str_remove(harbors$Harbor[each], ", [:print:]+")
  
  # Generate ranking message
  if (!is.na(tonnage_table[2, 1]) && tonnage_table[2, 1] != "") {
    if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
      # Scenario 3: GL and National ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes and the ", tonnage_table[3, 1], " largest harbor in the nation.")
    } else {
      # Scenario 2: Only GL ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes.")
    }
  } else if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
    # Scenario 4: Only National ranking available
    ranking <- paste0(short_harbor, " is the ", tonnage_table[3, 1], " largest harbor in the nation.")
  } else {
    # Scenario 1: No ranking available
    ranking <- ""
  }
  
  
  
  # Pasting text together
  if (is.na(tonnage_table[13,1])) {
    commodity_shipped <- ""
  } else {
    commodity_shipped <- paste("The largest commodity shipped is", tonnage_table[13,1], ".")
  }
  
  if (is.na(tonnage_table[15,1])) {
    commodity_received <- ""
  } else {
    commodity_received <- paste("The largest commodity received is", tonnage_table[14,1], ".")
  }
  
  talking_points <- paste0(
    harbors$Harbor[each], " had ", tonnage_table[5,1], " tons move through the harbor in ", calendar_year, 
    ", and averaged ", tonnage_table[7,1], " tons over the past 5 years from ", calendar_year-4, "-", calendar_year, ". ", 
    ranking, 
    " On average, between ", calendar_year-4, "-", calendar_year, ", the harbor shipped ", tonnage_table[8,1], 
    " tons and received ", tonnage_table[9,1], " tons annually. The top commodities handled at ", short_harbor, 
    " are ", tonnage_table[12,1], ". ", commodity_shipped, " ", commodity_received
  )
  
  writeData(wb, sheet = "Harbors", harbors$Harbor[each], startCol = 1, startRow = each+1)
  writeData(wb, sheet = "Harbors", talking_points, startCol = 2, startRow = each+1)

  }

#Talking points Version 2 Loop (i.e. Conneaut, OH is a deep draft commercial harbor which handled 4.3 Million tons of cargo, including Iron Ore (97%),
#... Limestone (1%), Slag (2%) in 2021. Conneaut is the 17th largest commercial harbor on the Great Lakes and the 83rd largest harbor in the nation. 
#... Waterborne transportation facilitated by the harbor supports $IDK How MUCh in business revenue, infinite -1  direct, indirect, and induced jobs,
#... and we do not want to wrok for real in labor income to the transportation sector.
## for ...in loop ==> for (each in 1:length(harbors$Harbor)) {
  
  tonnage_table <- fast_facts(harbors$Harbor[each])
  
  if (each == 1) {
    writeData(wb, sheet = "Tonnage_Tables", tonnage_table, startCol = 1, startRow = 1, rowNames = TRUE)
  } else {
    writeData(wb, sheet = "Tonnage_Tables", tonnage_table, startCol = 1, startRow = ((each-1)*19)+1, rowNames = TRUE)
  }
  
  short_harbor <- str_remove(harbors$Harbor[each], ", [:print:]+")
  
  # Generate ranking message
  if (!is.na(tonnage_table[2, 1]) && tonnage_table[2, 1] != "") {
    if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
      # Scenario 3: GL and National ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes and the ", tonnage_table[3, 1], " largest harbor in the nation.")
    } else {
      # Scenario 2: Only GL ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes.")
    }
  } else if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
    # Scenario 4: Only National ranking available
    ranking <- paste0(short_harbor, " is the ", tonnage_table[3, 1], " largest harbor in the nation.")
  } else {
    # Scenario 1: No ranking available
    ranking <- ""
  }
  
  # Pasting text together
  talking_points <- paste0(
    harbors$Harbor[each], " is a deep draft commercial harbor which handled ", tonnage_table[5,1], " tons of cargo, including ", tonnage_table[12,1], " in ", calendar_year, ". ",ranking,
    " Waterborne transportation facilitated by the harbor supports $", tonnage_table[15,1], " in business revenue, ", tonnage_table[16,1], " direct, indirect, and induced jobs, and ",
    tonnage_table[17,1], " in labor income to the transportation sector."
  )
  
  writeData(wb, sheet = "Harbors", harbors$Harbor[each], startCol = 1, startRow = each+1)
  writeData(wb, sheet = "Harbors", talking_points, startCol = 2, startRow = each+1)
  
}
# Vectorized operation to get tonnage tables for all harbors. lapply instead of for in loop
tonnage_tables <- lapply(harbors$Harbor, fast_facts) # (process all harbors simultaneously, call upon fastfacts funtion)
for (i in seq_along(harbors$Harbor)) {
  harbor <- harbors$Harbor[i]
  tonnage_table <- tonnage_tables[[i]]
  
  # Write tonnage_table
  writeData(wb, sheet = "Tonnage_Tables", tonnage_table, startCol = 1, startRow = (i - 1) * 19 + 1, rowNames = TRUE)
  
  short_harbor <- gsub(", [:print:]+", "", harbor)
  
  # Generate ranking message
  if (!is.na(tonnage_table[2, 1]) && tonnage_table[2, 1] != "") {
    if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
      # Scenario 3: GL and National ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes and the ", tonnage_table[3, 1], " largest harbor in the nation.")
    } else {
      # Scenario 2: Only GL ranking available
      ranking <- paste0(short_harbor, " is the ", tonnage_table[2, 1], " largest commercial harbor on the Great Lakes.")
    }
  } else if (!is.na(tonnage_table[3, 1]) && tonnage_table[3, 1] != "") {
    # Scenario 4: Only National ranking available
    ranking <- paste0(short_harbor, " is the ", tonnage_table[3, 1], " largest harbor in the nation.")
  } else {
    # Scenario 1: No ranking available
    ranking <- ""
  }
  
  # Generate talking points
  talking_points <- paste0(
    harbor, " is a deep draft commercial harbor which handled ", tonnage_table[5,1], " tons of cargo, including ", tonnage_table[12,1], " in ", calendar_year, ". ", ranking,
    " Waterborne transportation facilitated by the harbor supports $", tonnage_table[15,1], " in business revenue, ", tonnage_table[16,1], " direct, indirect, and induced jobs, and ",
    tonnage_table[17,1], " in labor income to the transportation sector."
  )
  
  # Write data
  writeData(wb, sheet = "Harbors", harbor, startCol = 1, startRow = i + 1)
  writeData(wb, sheet = "Harbors", talking_points, startCol = 2, startRow = i + 1)
}


#Create the file and get your strings! Run one loop at the time and then run this last  2 lines of code:) Check on your main directory for the file.
file = paste0("GL_Talking_Points_CY", calendar_short, ".xlsx")
saveWorkbook(wb, file, overwrite = TRUE)
#Close the file if you are re-running the loop and the file creator. 